image: node:12.16

before_script:
    # https://docs.gitlab.com/ee/ci/ssh_keys/#how-it-works
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - node --version
    - npm --version
    - yarn --version
    - eval $(ssh-agent -s)
    - echo "$DOCKER_RUNNER_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - date

pages:
    script:
        - yarn
        - yarn build
        - mv ./dist ./public
    artifacts:
        paths:
            - public